name: "setup-r"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test-macOS:
    runs-on: macOS-latest
    strategy:
      matrix:
        r: ['3.5.3', '3.6.1']
    steps:
      - name: Setup R
        uses: jimhester/setup-r@master
        with:
          r-version: ${{ matrix.r }}
      - run: R -e 'install.packages("remotes")'
  test-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        r: ['3.5.3', '3.6.1']
    steps:
      - name: Setup R
        uses: jimhester/setup-r@master
        with:
          r-version: ${{ matrix.r }}
      - run: R -e 'install.packages("remotes")'
  test-linux-container:
    runs-on: ubuntu-latest
    container: rstudio/r-base:3.6-xenial
    steps:
      - name: Setup R
        uses: jimhester/setup-r@master
      - run: R -e 'install.packages("remotes")'
  test-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        r: ['3.5.3', '3.6.1']
    steps:
      - name: Setup R
        uses: jimhester/setup-r@master
        with:
          r-version: ${{ matrix.r }}
      - run: R -e 'install.packages("remotes")'
