name: "setup-r"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test-macOS:
    runs-on: macOS-latest
    strategy:
      matrix:
        r: ['3.5', '3.6.x']
    steps:
      - name: Setup R
        uses: jimhester/setup-r@master
        with:
          r-version: ${{ matrix.r }}
      - run: R -e 'install.packages("remotes")'
  test-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        r: ['3.4', '3.x']
    steps:
      - name: Setup R
        uses: jimhester/setup-r@master
        with:
          r-version: ${{ matrix.r }}
      - run: R -e 'install.packages("remotes")'
  test-linux-container:
    strategy:
      matrix:
        r: ['3.5', '3.6']
    runs-on: ubuntu-latest
    container: rstudio/r-base:${{ matrix.r }}-xenial
    steps:
      - name: Setup R
        uses: jimhester/setup-r@master
      - run: R -e 'install.packages("remotes")'
  test-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        r: ['3.3', '3.2.1']
    steps:
      - name: Setup R
        uses: jimhester/setup-r@master
        with:
          r-version: ${{ matrix.r }}
      - run: R -e 'install.packages("remotes")'
