name: "Test setup-r action"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    runs-on: macOS-latest
    steps:
      - uses: jimhester/setup-r@releases/v1
      - run: R -e 'print("hi")'
      - run: R -e 'install.packages("remotes")'
